name: Build and Test Kotlin App

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./exchange

      - name: Build and Test with Gradle
        run: ./gradlew clean build test --info
        working-directory: ./exchange
